Two prompts:
prompt 1:
I have an incomplete project with a jumble of 'Vue2 Component's and 'Vue2.7+ SFC's in the components/ directory of the project but everything else from a proper Vue 3 application is missing. Some of the Vue2.7+ SFCs have .js extensions but they are not .js files, treat them as .vue files. If you need to convert Vue 2 components into Vue 3 SFCs, do so. I want you to turn this project into a proper Vue 3 project for me as if I started from scratch and just added in the components/*.vue files in. The Vue 3 application make use of and display all of the vue 3 components that we have.

prompt 2:
fix this error:
Could not resolve "./components/SimpleHeader.vue" from "src/App.vue"
file: /home/henrymai/workspace/fastapichat/projects/Tennis_Racket_Marketplace_1723700032/src/App.vue
error during build:
RollupError: Could not resolve "./components/SimpleHeader.vue" from "src/App.vue"
    at error (file:///home/henrymai/workspace/fastapichat/projects/Tennis_Racket_Marketplace_1723700032/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/henrymai/workspace/fastapichat/projects/Tennis_Racket_Marketplace_1723700032/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at file:///home/henrymai/workspace/fastapichat/projects/Tennis_Racket_Marketplace_1723700032/node_modules/rollup/dist/es/shared/node-entry.js:24822:26